
services:
  db:
    image: mysql:5.7
    container_name: mydocs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydocs_database
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydocs-php
    restart: always
    volumes:
      - ./htdocs:/var/www/html
      - ./php-upload-limits.ini:/usr/local/etc/php/conf.d/php-upload-limits.ini:ro
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'OK';"]
      interval: 5s
      timeout: 1s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: mydocs-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./htdocs:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 10s
      timeout: 1s
      retries: 3

volumes:
  db_data:
